source 'https://rubygems.org'

gem 'glimmer-dsl-libui', '~> 0.7.4'
gem 'mysql2'
gem 'rubocop', group: 'development'
gem 'win32api'
gem "minitest"
gem 'sinatra', '~> 3.0', '>= 3.0.6'
gem 'thin', '~> 1.8', '>= 1.8.2'
gem 'student_MyGem'